### ISSUE TITLE
Periksa isu-isu terdahulu bersama salinan dokumentasi

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#21]
Senarai isu terdahulu yang patut diperiksa:

* [x] Kajian projek tercipta #2 --> `docs/kajian/*`
* [x] Soal kesesuaian takrif #11 --> `docs/{kajian,panduan}/*`
* [x] Penyelesaian selisih terjemah #13 --> `docs/panduan/*`
* [x] Penyelesaian kesulitan terjemah tunggal #14 --> `docs/panduan/*`

Semakan bersahaja M baru-baru ini mendapati isu-isu tersebut mungkin mengandungi maklumat yang tidak terdapat dalam mana-mana fail dokumentasi di repositori pada masa isu ini dicipta. Sekiranya benar ada maklumat yang tertinggal, wajar disalin dan disimpan sebagai panduan.

**3 Disember 2018**: Salinan dokumentasi telah selesai disemak pada hari ini.

Terbitan dalam rancangan: `1.2.0`

**Comment by kmubiin** [comment]
> Semakan bersahaja M baru-baru ini mendapati isu-isu tersebut mungkin mengandungi maklumat yang tidak terdapat dalam mana-mana fail dokumentasi di repositori pada masa isu ini dicipta. Sekiranya benar ada maklumat yang tertinggal, wajar disalin dan disimpan sebagai panduan.
> 
> Terbitan dalam rancangan: `1.2.0`

Salinan dokumentasi telah selesai disemak pada hari ini.
